### PR TITLE
Multiple search terms in incremental search

### LINKED ISSUE #81: allow multiple search terms in rcloud.search.description
If multiple (spaced separated) words are passed in then we would like to match as fuzzily as possible.

c.f. att/rcloud#2518

In @gordonwoodhull 's words

> I forgot this was going through Lucene. I don't know if Lucene supports this, but my preferred behavior would be term1 followed by term2 followed by term3. (in regexp, /term1.*term2.*term3/)
>Barring that, an implied AND would be fine. I don't think there's any point to considering OR for incremental search, and I'd rather people didn't have to use Lucene syntax here.
>Example usage: type a fragment of a folder name, space, fragment of notebook name.

So we can split the description argument on spaces and recombine using whichever Lucene syntax we need.

### PR DESCRIPTION
**Pull request by bashlee**
Fixes #81 
Multiple search terms now handled with AND operator

### CODE REVIEW

**Review by dougmet — COMMENTED** [review]
I like this. If there are some edge cases we haven't thought of we can cross that when we get there.

Only edge case I can think for now. What happens if someone searches for `folder/name` does the slash cause trouble with Lucene or will it go through unphased?

**Comment by gordonwoodhull** [comment]
Hi @dougmet, looks like this never got merged. 

I just gave it a test run and it seems to work well, could you take another look?

**Comment by dougmet** [comment]
My bad, I had wanted to test the slash-separator case. I’ll have a go later today/early tomorrow and merge if it’s OK or push a fix.

**Comment by gordonwoodhull** [comment]
Ah, got it. Yes, it does seem that `/` breaks it. In fact, typing any search string with `/` produces errors:

```
TypeError: Cannot read property 'docs' of undefined
at https://rcloud-2.research.att.com/js/rcloud_bundle.js:13346:44
From previous event:
at https://rcloud-2.research.att.com/js/rcloud_bundle.js:13344:84
From previous event:
at notebook_tree_search_service.get_results (https://rcloud-2.research.att.com/js/rcloud_bundle.js:13343:20)
at HTMLInputElement.<anonymous> (https://rcloud-2.research.att.com/js/rcloud_bundle.js:13436:37)
at HTMLInputElement.dispatch (https://rcloud-2.research.att.com/lib/js/jquery-2.1.1.js:4409:9)
at HTMLInputElement.elemData.handle (https://rcloud-2.research.att.com/lib/js/jquery-2.1.1.js:4095:28)
```

Parens and all kinds of braces do too. I know we are kind of misusing Lucene here, but it works great, so we should probably sanitize the input.

**Comment by bashlee** [comment]
Pushed fix to include /\ and + as separators when searching folder trees

**Comment by dougmet** [comment]
Great, thanks @bashlee

**Pull request merged**
